### ISSUE TITLE
Suggestion: Truncate by word in addition to character #

### ISSUE THREAD

**Issue by CKolkey** [code-biscuits/nvim-biscuits#13]
For example, in the biscuit config, you could say `word_limit = 1` and it will only print the first word (space delimited). I think this is a little more clever than character count

**Comment by cmgriffing** [comment]
Awesome thanks. I added this to the Project board. It will probably be pretty easy to knock out when I get a chance to work on this again soonish.

**Comment by cmgriffing** [comment]
Thanks again, I like this idea and will probably bring it into the VSCode plugins too.

Alright @CKolkey , try it out. There is now a `trim_by_words` boolean config option. The docs should help. If there is more that I need to add to the docs to make it easier to configure, just let me know.

**Comment by CKolkey** [comment]
Seems to be working fine, thanks :)
