### ISSUE TITLE
table.move does not exist in LuaJIT 2.0

### ISSUE THREAD

**Issue by nogweii** [code-biscuits/nvim-biscuits#15]
Running the plugin on Arch Linux, it compiles with the version of LuaJIT in the `[community]` repo -- 2.0.5. This version of LuaJIT targets Lua 5.1, which does not include `table.move()`. It was added in Lua 5.3, which is the version targeted by LuaJIT 2.1. However, LuaJIT 2.1 is still marked as beta, so Arch doesn't ship it.

Test case: https://gist.github.com/nogweii/3a814dee606413916e6532710a6155be

This means running the plugin with this set of libraries results in an error when neovim is starting:

```
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ...ack/packer/opt/nvim-biscuits/lua/nvim-biscuits/utils.lua:18: attempt to call field 'move' (a nil value)
```

**Comment by cmgriffing** [comment]
I refactored table.move into just a for loop. Try it again when you can.

**Comment by nogweii** [comment]
Yup, it's working now!
