### ISSUE TITLE
Feature Request: Toggle virtual text

### ISSUE THREAD

**Issue by ekickx** [code-biscuits/nvim-biscuits#17]
Hello, I want to request a feature to toggle the virtual text. But of course as long as you also want to add this feature.

**Comment by cmgriffing** [comment]
I like this idea. I'm not sure what the best approach is yet. I'm guessing a configurable key binding would make sense. Right?

**Comment by ekickx** [comment]
By configurable keybinding do you mean something like this:

```lua
require('nvim-biscuits').setup({
  keys = "<Leader>tb"
})
```

**Comment by cmgriffing** [comment]
Ok, I have something that I think will work for everyone. The option for setting a binding via the config is there. But the function is exposed for you to bind manually instead.

Go ahead over to the PR and let me know what you think.

#18

**Comment by ekickx** [comment]
Ahhh sorry for the late reply. I will try it
