### ISSUE TITLE
BufEnter is too often to call attach

### ISSUE THREAD

**Issue by tjdevries** [code-biscuits/nvim-biscuits#2]
https://github.com/code-biscuits/nvim-biscuits/blob/c7df38034116cf1cfd5c86fd7e57f29a50e5ccfb/plugin/nvim-biscuits.vim#L8

This means that every time you enter a buffer (so if you have a split, and you move back and forth between them) you'll attach and re-attach every time.

Or you can check if you're currently attached to a buf and then short-circuit in your BufferAttach code.

**Comment by cmgriffing** [comment]
Cool.

> Or you can check if you're currently attached to a buf and then short-circuit in your BufferAttach code.

That sounds like the approach we will take. Thanks.
