### ISSUE TITLE
Highlight Group not Working

### ISSUE THREAD

**Issue by axieax** [code-biscuits/nvim-biscuits#21]
Not too sure why but set highlight group using either `vim.cmd([[highlight BiscuitColor ctermfg=cyan]])` or `vim.api.nvim_set_hl(0, "BiscuitColor", { ctermfg = "cyan" })` doesn't seem to work (using lua) - am I doing this wrong?

Here is my config:
![image](https://user-images.githubusercontent.com/62098008/139672771-d4cf1dcd-b30a-4278-80ef-b2c309414430.png)

p.s. is there a way to not automatically decorate_nodes on startup? - i'm currently just calling toggle again in my setup function to disable it

**Comment by cmgriffing** [comment]
Interesting. I haven't done any of the vim.cmd stuff yet, so I will have to check that out.

To your second point, I should probably add a config setting to set whether it tries on start or not. Thanks, I will probably be able to put some time into this during the weekend.

**Comment by cmgriffing** [comment]
I was able to make a PR for the biscuits to be hidden by default for toggle_keybind users.
https://github.com/code-biscuits/nvim-biscuits/pull/24

Let me know if that branch works for you and feel free to comment on the PR letting me know if it works

I will leave this issue open for the main bug related to highlight groups for now.

**Comment by axieax** [comment]
> I was able to make a PR for the biscuits to be hidden by default for toggle_keybind users. #24
> 
> Let me know if that branch works for you and feel free to comment on the PR letting me know if it works
> 
> I will leave this issue open for the main bug related to highlight groups for now.

Hi the PR looks good, thanks for that! Looking forward to seeing the working HL groups soon :))

**Comment by cmgriffing** [comment]
Ok, I was finally able to get my local config to use a lua config script.

I don't know what to say but it works on my machine on the latest main branch code.

```lua
-- " global color
vim.cmd [[highlight BiscuitColor ctermfg=cyan]]


-- " language specific color
vim.cmd [[highlight BiscuitColorRust ctermfg=red]]
vim.cmd [[highlight BiscuitColorGo ctermfg=35]]
```

![image](https://user-images.githubusercontent.com/1195435/141708481-28dc37b2-5f54-496d-8284-33a89ba76883.png)

**Comment by axieax** [comment]
Interesting, not sure if there's anything wrong with my order of configuration then..
- [Plugin manager](https://github.com/axieax/dotconfig/blob/6b43f85396b0c782cb52dc9f6d950629afc500cf/nvim/lua/plugins/init.lua#L324-L328)
- [Config](https://github.com/axieax/dotconfig/blob/6b43f85396b0c782cb52dc9f6d950629afc500cf/nvim/lua/plugins/biscuits.lua)

I'm currently on version 0.5.1. Appreciate the effort!!

**Comment by cmgriffing** [comment]
I will see if I can reproduce by switching how I do my config to look closer to yours. (plugins folder, etc). Probably won't be able to try til next week though. I'm going to leave this issue open for tracking it though.

**Comment by axieax** [comment]
Appreciate the efforts! Not sure if this helps, but I had a similar issue with highlight groups for indent-blankline.nvim not being set (well being overriden). It turned out that my theme material.nvim overwrote my highlights. I've checked my themes already and could not find any which would overwrite this highlight group, so not too sure what to do from here ahaaha

**Comment by cmgriffing** [comment]
I feel like its been a while. @axieax is there any chance that this has been resolved in the mean time? No worries if not. Just wanted to double check on the status of this issue.

**Comment by axieax** [comment]
Oh yes sorry forgot to close this issue, but it has been resolved. I believe setting it via a ColorScheme autocmd, or defining it within a colorscheme's config options should work as well, although I no longer have a need for this so am not sure atm.

**Comment by Anseryde** [comment]
This issue has reappeared for me recently

**Comment by cmgriffing** [comment]
@Anseryde Try using a different theme or default theme. A previous user mentioned that their theme was overriding the highlight groups. Let me know if that works or not.
