### ISSUE TITLE
<br /> Breaks the order of biscuits 

### ISSUE THREAD

**Issue by PetitBandit** [code-biscuits/nvim-biscuits#22]
![biscruits](https://user-images.githubusercontent.com/32488040/139854804-c7e9fdb0-0d11-4b2c-90e6-1d6cc9303a28.png)

I have this while working on a react file, the biscuit returns the end of p.p1 while it s just the end of the <br />
any hints on how i could fix this please ?

**Comment by cmgriffing** [comment]
This is an interesting bug. I will have to look into it.

**Comment by cmgriffing** [comment]
Thanks. I did some digging and was able to reproduce that exact bug in an HTML file, but not jsx.

Could you provide some more details? What was the file name/extension?

In the meantime, here is the branch that fixed my reproduction: https://github.com/code-biscuits/nvim-biscuits/tree/feature-html-only-decorate-elements

Feel free to pull it down and try it out. I will be making a PR. Feel free to comment here or there.

**Comment by PetitBandit** [comment]
Its a .js file called Sequence2.js that uses react. What kind of other details can I provide ? (Since it s a work file, i cant really share the whole thing). I could if that would help try to reproduce by creating another file if that helps ?

**Comment by cmgriffing** [comment]
Ok thanks. Yeah the fixes I did are only for HTML files at the moment.

I will dig into trying to reproduce it in my local code, but if you end up creating an example file that is not work-related, let me know.

**Comment by cmgriffing** [comment]
Try pulling down from that same branch again. Was able to get it fixed in js, jsx, and html files for that same reproduction.

**Comment by PetitBandit** [comment]
I did try and it seem to have fixed the issue for me, br doesn t affect the p.p1 anymore !

Thank you so much !

**Comment by cmgriffing** [comment]
No worries thanks for the report. I will get that merged into the main branch soon.
