### ISSUE TITLE
Could not set highlight for languages containing "-"

### ISSUE THREAD

**Issue by axieax** [code-biscuits/nvim-biscuits#27]
For buffers where TS parser returns a language containing "-", the following error will be displayed on BufEnter:
![image](https://user-images.githubusercontent.com/62098008/141227594-7aeb4b84-310e-4c00-a45a-6af3f29be6d9.png)

This is due to the highlight command not being able to accept the "-" character. I've found the fix already for this and will add a PR soon!

**Comment by cmgriffing** [comment]
Oh interesting. Just for so I understand, which language was causing this? I should probably just be parsing out the dash. Just looking for examples to test with.

**Comment by axieax** [comment]
Hi it's mostly external plugins for me:
code-action-menu-warning-message for https://github.com/weilbith/nvim-code-action-menu
dap-repl for https://github.com/mfussenegger/nvim-dap

**Comment by axieax** [comment]
Yep parsing out the dash seems to make this bug disappear as well! I've updated the PR now :))
