### ISSUE TITLE
Logging location suggestion

### ISSUE THREAD

**Issue by axieax** [code-biscuits/nvim-biscuits#30]
Hi, just realised that this plugin logs to the home directory as a non-hidden file. Do you think it'll be better if logs go to the standard cache directory, like plugins such as nvim itself, lsp, null-ls, telescope and a few others? This path is `vim.fn.stdpath("cache") .. "/" .. "null-ls.log"`. If you're happy with this change, I can make a PR for it :))

**Comment by cmgriffing** [comment]
Yeah that is a great idea. Feel free to make the PR. Thanks.
