### ISSUE TITLE
More introduce

### ISSUE THREAD

**Issue by yyy33** [code-biscuits/nvim-biscuits#33]
Can you introduce more of this plug-in, such as some pictures or videos, I read the documentation or do not know what the plug-in is doing

**Comment by cmgriffing** [comment]
I think that's fair. I will get something going for that.

In the meantime the functionality is mostly similar to: https://marketplace.visualstudio.com/items?itemName=CodeBiscuits.assorted-biscuits

This plugin actually has more features and supported languages, however the gif on that page does a good job of showing what it does.

Thanks for the feedback. I will leave this issue active until I have a gif for the README here.

**Comment by cmgriffing** [comment]
Thanks. I have added a gif to the README here.
