### ISSUE TITLE
Python-specific language parser is broken

### ISSUE THREAD

**Issue by simplepad** [code-biscuits/nvim-biscuits#35]
The `transform_text` function inside the python-specific language parser is defined as:

https://github.com/code-biscuits/nvim-biscuits/blob/5257ea28f377bc6ec0371f9bcbafdd4c6306199a/lua/nvim-biscuits/languages/python.lua#L11

and the `bufnr` parameter is used on line 27:

https://github.com/code-biscuits/nvim-biscuits/blob/5257ea28f377bc6ec0371f9bcbafdd4c6306199a/lua/nvim-biscuits/languages/python.lua#L27-L28

However, when this function is called inside of languages.lua, only the first two parameters are passed to it: 

https://github.com/code-biscuits/nvim-biscuits/blob/5257ea28f377bc6ec0371f9bcbafdd4c6306199a/lua/nvim-biscuits/languages.lua#L28

so it throws an error every time you open a python file.

**Comment by cmgriffing** [comment]
Oh good catch. That must have come during a refactor. The fix should be easy.
I will think about how to create a regression test for this.

I will try and get to it this Sunday if that works.

**Comment by cmgriffing** [comment]
You were more than right. There were a bunch of places missing the `bufnr` that was already being passed in to their outer context.

Give the latest code on main a try.

**Comment by simplepad** [comment]
Awesome, no more errors!
