### ISSUE TITLE
Confusing Output from Python

### ISSUE THREAD

**Issue by Julian** [code-biscuits/nvim-biscuits#4]
Hi.

This plugin looks interesting -- I was attempting to try it out on a Python file though and appear to get some confusing results. I put a side by side below of on the left what this plugin is annotating, and on the right the bare file for comparison, though it's just this one, as an example: https://github.com/Julian/jsonschema/blob/main/docs/jsonschema_role.py

<img width="1440" alt="Screen Shot 2021-03-30 at 20 58 38" src="https://user-images.githubusercontent.com/329822/113075477-01bc2d00-919b-11eb-9e23-b439e91b53e7.png">

I don't understand really any of the annotations being added -- it seems in some cases perhaps `nvim-biscuits` is confused by the reST syntax in docstrings perhaps? Or why it's trying to show me `// try:` below the `try/except` block (where that's not part of the `try`). I don't understand either why it's using `//` to show things, which isn't the right comment character for Python, but perhaps that's a default? All I did was call `require('nvim-biscuits').setup{}` as per the README.

I'm using `pyls`, and `c7df38034116cf1cfd5c86fd7e57f29a50e5ccfb` of this plugin on macOS (M1). If there's anything else I can share about my setup lemme know obviously!

**Comment by cmgriffing** [comment]
Thanks. Yes, I haven't done enough testing with Python, but I think we can do some language specific handling like we do with html, js, vue currently.

Leaving this open so I can track it. Also any viewers please thumbs up the issue if you are also waiting for better python support.

**Comment by Julian** [comment]
Thanks! To be honest I don't know what I expected/wanted out of this for Python, I'd have to think about it, it was just the first thing I tried. Will give a shot at HTML for a better idea of something more in the current wheelhouse. Appreciated!

**Comment by Julian** [comment]
With another few seconds of thought :), I guess a few obvious things immediately come to mind that should indeed apply to Python, like showing the variable name at the closing delimiter of a (long/multiline) container, and/or the same for a long function or class (showing the name of it at the end), etc.

**Comment by cmgriffing** [comment]
Ok, so I did something to help improve the output. Try it out if you get a chance. I expect to have to do more still.

Basically, in some cases the biscuit would show the text from the first line of the inside of a block rather than the start of the block itself.

If we can narrow down a few more specific cases where the output could improve more, we might be able to call this issue complete.

As an example, I think one more thing might be the fact that it is trying to annotate the contents of comment blocks. That might even be an issue in multiple languages though.

**Comment by cmgriffing** [comment]
A viewer on my stream tried the file in question and noted that the output is improved and what they would expect.

If there are more specific code snippet edge cases you notice, feel free to make a new issue for them specifically.
