### ISSUE TITLE
Not removing Biscuits when deleting a line

### ISSUE THREAD

**Issue by davvil** [code-biscuits/nvim-biscuits#45]
When I delete a line (e.g. with `dd`) , the biscuit associated with the line stays, without any way to remove it (AFAICT).

I'm using the cusor_line_only option, in case this is relevant.

**Comment by cmgriffing** [comment]
Interesting. Thanks for reporting this. I will have to look into it.

Have you tried without cursor_line_only as well? No worries if not, just curious.

**Comment by davvil** [comment]
Just tried it. Same thing happens without cursor_line_only.

**Comment by davvil** [comment]
FWIW, adding a call to `nvim_buf_clear_namespace` before the [`while has_nodes` loop in `init.lua`](https://github.com/code-biscuits/nvim-biscuits/blob/main/lua/nvim-biscuits/init.lua#L45) solves the problem for the case when `cusor_line_only` is set. However it introduces additional issues in case it is not set, moving the biscuit to an incorrect line.

**Comment by cmgriffing** [comment]
> FWIW, adding a call to `nvim_buf_clear_namespace` before the [`while has_nodes` loop in `init.lua`](https://github.com/code-biscuits/nvim-biscuits/blob/main/lua/nvim-biscuits/init.lua#L45) solves the problem for the case when `cusor_line_only` is set. However it introduces additional issues in case it is not set, moving the biscuit to an incorrect line.

That is a great fix. I'm not sure that is a new bug with the biscuit being on the wrong line. It is likely just a failure of the tree-sitter parser because the code no longer actually validates in the cases I have seen.
