### ISSUE TITLE
Fails when opening vim help files

### ISSUE THREAD

**Issue by gustavooferreira** [code-biscuits/nvim-biscuits#46]
Errors when opening **_some_** help files but not all, weirdly enough.
It will error the first time I issue a help command on a newly started instance. When I press enter it shows the help file.
If I quit the window with the help file and open it again, no longer errors (most likely cos the buffer with the help file stayed around?)

Commands I've used to replicate the bug:
```
:help quickfix

or

:help syntax

or

:help autocmd
```

Just running `:help` on a newly started neovim instance works without any errors.

<img width="1337" alt="Screenshot 2023-05-27 at 22 07 52" src="https://github.com/code-biscuits/nvim-biscuits/assets/17534422/a183c9cc-1845-4271-9428-95d41aea8ded">

**Comment by gustavooferreira** [comment]
Disabled biscuit for `vimdoc` as I don't really need it there and the error went away.

**Comment by cmgriffing** [comment]
Sorry for taking so long to get to this. It looks like I have a bug for vimdoc files so that is hugely useful. I will look into a fix when I can. I'm glad you got things working for your use-case in the meantime, though.

**Comment by corintho** [comment]
I am currently facing this issue as well. @gustavooferreira any tips on how to disable it?

**Comment by cat-phish** [comment]
> I am currently facing this issue as well. @gustavooferreira any tips on how to disable it?

This is what did it for me. Adding vimdoc made it go away

```
         language_config = {
            help = {
               disabled = true
            },
            vimdoc = {
               disabled = true
            },
```

**Comment by cmgriffing** [comment]
> > I am currently facing this issue as well. @gustavooferreira any tips on how to disable it?
> 
> This is what did it for me. Adding vimdoc made it go away
> 
> ```
>          language_config = {
>             help = {
>                disabled = true
>             },
>             vimdoc = {
>                disabled = true
>             },
> ```

I will add this to the default config. I think it makes sense that way.
