### ISSUE TITLE
FR: Disable on big files

### ISSUE THREAD

**Issue by chrisgrieser** [code-biscuits/nvim-biscuits#48]
I noticed that biscuits causes nvim to become quite laggy on larger files (100Kb+). As far as I can tell, there is only an option to disable biscuits on specific filetypes – could there maybe also be an option to disabled based on filesize? (or more generally, a user-supplied function which determines whether biscuits should attach to buffer or not)

**Comment by cmgriffing** [comment]
@chrisgrieser Check out the latest version. I have added a config setting to allow setting a max file size

https://github.com/code-biscuits/nvim-biscuits?tab=readme-ov-file#configuration-max-file-size

closed by #49
