### ISSUE TITLE
utils.lua:43: attempt to index local 's' ( a nil value)

### ISSUE THREAD

**Issue by creativenull** [code-biscuits/nvim-biscuits#9]
Hey!

I've been having this issue for a while, thought I would post it here. Every time I move the lines up or down (check keybindings below image) or undo with <kbd>u</kbd>, I get the issue shown below:

![screenshot](https://user-images.githubusercontent.com/3767728/114336234-7b013b80-9b1c-11eb-82fb-696eb10bde25.png)

The way I move the lines up and down is via these keybindings:

```
nnoremap <M-j> mz:m+<CR>`z
nnoremap <M-k> mz:m-2<CR>`z
vnoremap <M-j> :m'>+<CR>`<my`>mzgv`yo`z
vnoremap <M-k> :m'<-2<CR>`>my`<mzgv`yo`z
```

However, the issue does **NOT** happen when I cut and paste lines via <kbd>dd</kbd> (cut) and <kbd>p</kbd> (paste).

After further investigating, it looks like the trim function just trims any input without validating that the argument being passed is a valid string.

A solution I found to get rid this error was to check if the string is not nil and if not then trim it, else return an empty string. Not sure if anyone else is having this issue, but thought this here before I make a PR for this fix.

**Comment by creativenull** [comment]
Here is what I did to get rid of the error by adding an if condition to check for `nil`, at line 42 of `lua/nvim-biscuits/utils.lua` file:

```lua
utils.trim = function(s)
  if s == nil then return '' end

  return s:match'^()%s*$' and '' or s:match'^%s*(.*%S)'
end
```

**Comment by cmgriffing** [comment]
Thanks for the PR too. Merged.
